# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireServiceapp', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
