# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireServiceapp', '0007_auto_20180412_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
