# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireServiceapp', '0008_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
