# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireServiceapp', '0009_auto_20180412_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
