# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireServiceapp', '0010_auto_20180412_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_size',
            field=models.IntegerField(default=0),
        ),
    ]
